#! /bin/bash

# Program to output a system information page

title="System Information Report"

echo "<HTML>
         <HEAD>
               <TITLE>$title</TITLE>
         </HEAD>
         <BODY>
                <H1>$title</H1>
         </BODY>
</HTML>"
